---
title: "p-values"
author: "Hanna Choi"
date: "5/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### just added
```{r}
library(tidyverse)
wrc <- gather(rc, key= "type", value = frequency, "_C_12_AB_M_17_", "_C_19_AB_M_16_", "_C_14_AB_M_27_", "_C_30_AB_M_14_", "_C_4_AB_M_08_", "_C_7_AB_M_07_"  ,"_H_30_AB_M_11_"  ,"_H_28_AB_M_03_","_H_11_AB_M_13_", "_H_17_AB_M_18_"  ,   "_H_26_AB_M_12_"   ,  "_H_2B_M_02_"    ,    "_H_2_AB_M_23_", "_H_32_AB_M_20_"   ,  "_H_34_AB_M_01_"    , "_H_4_AB_M_05_"   ,   "_C_19_AB_O_26_"  , "_C_27_AB_O_21_"    , "_C_12_AB_O_25_"     ,"_C_14_AB_O_09_"   ,  "_C_34_AB_O_10_" , "_C_4_AB_O_04_", "_H_17_AB_O_22_",  "_H_11_AB_O_24_"    , "_H_2_AB_O_15_","_H_32_AB_O_19_", "_H_4_AB_O_06_")

wrc$type <- gsub("_C_\\d+_AB_M_\\d+_","C_M", wrc$type)
wrc$type <- gsub("_H_\\d+_AB_M_\\d+_","H_M", wrc$type)
wrc$type <- gsub("_C_\\d+_AB_O_\\d+_","C_O", wrc$type)
wrc$type <- gsub("_H_\\d+_AB_O_\\d+_","H_O", wrc$type)
wrc$type <- gsub("_H_2B_M_\\d+_","H_M", wrc$type)
wrc <- wrc %>% arrange(row.identity)
library(dplyr)
```
```{r}
wrc_list <- split(wrc, f=list(wrc$type,wrc$row.identity))
foo <- 1:768
nth_element <- function(vector, starting_position, n) { 
  vector[seq(starting_position, length(vector), n)] 
  }
x_1_4<-nth_element(foo,1,4)
x_2_5<-nth_element(foo,2,4)
x<-append(x_1_4,x_2_5)
rx<-x[order(x)]
wrc_list[["C_M.CoQ10"]][["row.identity"]]
```
### was here
```{r}
mttest <- list()
j <- 1
i <- 1
for (i in rx){
    mttest[[j]] <- list(names(wrc_list[c(i,i+2)]),
                               t.test(wrc_list[[i]][["frequency"]],wrc_list[[(i+2)]][["frequency"]],
                                      alternative="g")$p.value, t.test(wrc_list[[i]][["frequency"]],wrc_list[[(i+2)]][["frequency"]],
                                      alternative="g")$estimate)

    
    j <- j+1
}
d <- as.data.frame(matrix(unlist(mttest), ncol=length(unlist(mttest[1])), byrow = TRUE))
d <- d %>%
  rename(Control = V1, Heated = V2, pvalues=V3)
do <- d %>%
   mutate(pvalues = as.numeric(as.character(pvalues)),
          V4 = as.numeric(as.character(V4)),
          V5 = as.numeric(as.character(V5))) %>%
   mutate(Diff = V4 - V5)
```
```{r}
library(DT)
datatable(do, options = list(), class = "display")
```

```{r}
dop <- do[c(1:53),] 
library(DT)
Organic <- dop[c(1,6,7,13,14,15,18,22,25,29,31,35,36,37,41,44,45,46,47,49),]
Mineral <- dop[c(2,3,4,5,8,9,10,11,12,16,17,19,20,21,23,24,26,27,28,30,32,33,34,38,39,40,42,43,48,50,51,52,53),]
write.csv(Organic, "Organic_Lipids.csv",row.names = TRUE)
write.csv(Mineral, "Mineral_Lipids.csv", row.names = TRUE)
do <- do[order(do$pvalues),]
write.csv(do, "ALL_Lipids.csv", row.names=TRUE)
```
