---
title: "ga_boxplot"
author: "Hanna Choi"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ggplot2)
library(scales)
data <- as.data.frame(read.csv("EMSL_PNNL.csv"), header=TRUE)
data_ga <- data[36,]
data_ga_wrangled <- data_ga %>% gather("M_C_4_AB",	"M_C_7_AB",	"M_C_12_AB",	"M_C_14_AB",	"M_C_19_AB",	"M_C_30_AB",	"M_H_2_AB",	"M_H_2B",	"M_H_4_AB",	"M_H_11_AB",	"M_H_17_AB",	"M_H_26_AB",	"M_H_28_AB",	"M_H_30_AB",	"M_H_32_AB",	"M_H_34_AB",	"O_C_4_AB",	"O_C_12_AB",	"O_C_14_AB",	"O_C_19_AB",	"O_C_27_AB",	"O_C_34_AB",	"O_H_2_AB",	"O_H_4_AB",	"O_H_11_AB",	"O_H_17_AB",	"O_H_32_AB", key="type", value="frequencies")
data_ga_wrangled$type <- c("Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Heated", "Organic Heated", "Organic Heated", "Organic Heated", "Organic Heated")
```
```{r boxplot of glyceric acid frequencies}
ga <- ggplot(data_ga_wrangled, aes(type, frequencies, fill=type))
boxga <- ga + geom_boxplot() + geom_point() +
  scale_fill_manual(values=c("#FAFAFA", "#808080","#B43757", "#830300")) +
  labs(title="glyceric acid Frequencies")
logboxga <- boxga + scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(.x))) + theme(legend.position = "none")
logboxga
png("glyceric_acid.png")
logboxga
while (!is.null(dev.list()))  dev.off()
```

