---
title: "L leucine boxplot"
author: "Hanna Choi"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
data <- as.data.frame(read.csv("EMSL_PNNL.csv"), header=TRUE)
data_Ll <- data[51,]
data_Ll_wrangled <- data_Ll %>% gather("M_C_4_AB",	"M_C_7_AB",	"M_C_12_AB",	"M_C_14_AB",	"M_C_19_AB",	"M_C_30_AB",	"M_H_2_AB",	"M_H_2B",	"M_H_4_AB",	"M_H_11_AB",	"M_H_17_AB",	"M_H_26_AB",	"M_H_28_AB",	"M_H_30_AB",	"M_H_32_AB",	"M_H_34_AB",	"O_C_4_AB",	"O_C_12_AB",	"O_C_14_AB",	"O_C_19_AB",	"O_C_27_AB",	"O_C_34_AB",	"O_H_2_AB",	"O_H_4_AB",	"O_H_11_AB",	"O_H_17_AB",	"O_H_32_AB", key="type", value="frequencies")
data_Ll_wrangled$type <- c("Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Controlled", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Mineral Heated", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Controlled", "Organic Heated", "Organic Heated", "Organic Heated", "Organic Heated", "Organic Heated")
```
```{r boxplot of frequencies}
Ll <- ggplot(data_Ll_wrangled, aes(type, log(frequencies), fill=type)) + 
  geom_boxplot() + 
  geom_point() +
  scale_fill_manual(values=c("#808080", "#800000", "#808080", "#800000")) +
  labs(title="L-leucine logged frequencies")
print(Ll)
png("L_leucine.png", width = 350, height = 350)
plot(Ll, nrow=2, ncol=1)
while (!is.null(dev.list()))  dev.off()
```

