---
title: "Boxplot_HvC"
author: "Hanna Choi"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
library(tidyr)
```

```{r adding averages to dataset}
data <- read.csv("EMSL_PNNL.csv", header=TRUE, row.names=1)
data$MCavg <- rowMeans(data[,1:6])
data$MHavg <- rowMeans(data[,7:16])
data$OCavg <- rowMeans(data[,17:22])
data$OHavg <- rowMeans(data[,23:27])
```
```{r looking at only the average frequencies}
avg <- as.data.frame(data[,28:31])
avg
```
```{r looking at only the quartile numbers}
df <- as.data.frame(quantile(data$MCavg))
df[,2] <- as.data.frame(quantile(data$MHavg))
df[,3] <- as.data.frame(quantile(data$OCavg))
df[,4] <- as.data.frame(quantile(data$OHavg))
df
```

```{r boxplot}
avg_wrangled <- avg %>% gather("MCavg", "MHavg", "OCavg", "OHavg", key="type", value="avg_frequencies")
avg_wrangled$log <- log(avg_wrangled[,2])
g <- ggplot(avg_wrangled, aes(x=type, y=log, fill=type), xlab=TRUE) + geom_boxplot()
g
```


