---
title: "metabolites"
author: "Hanna Choi"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(tidyverse)
library(readr)
library(stringr)
```
```{r kegg loaded}
load("~/Blanchard_Lab/R/Proteomics/KEGG/KEGGdata/data/kegg_compounds.rda")
EMSL_PNNL <- read_csv("~/Blanchard_Lab/R/Proteomics/EMSL_PNNL.csv")
```

```{r building match before manual edit}
Metabolitelist <- EMSL_PNNL[,'Metabolite']
x <- data.frame()
# x has keyword;
for (i in 1:nrow(Metabolitelist)){
  kegg <- kegg_compounds[grepl(paste(Metabolitelist[i,], ";", sep = ""), kegg_compounds$NAME, ignore.case = TRUE),]
  if (nrow(kegg) != 0){
    kegg$met <- paste0(Metabolitelist[i,1],".", i)
    x <- rbind(x, kegg)
  }
  else rm(kegg)
}
#x has keyword being beginning of NAME
for (i in 1:nrow(Metabolitelist)){
  kegg <- kegg_compounds[grepl(paste0("^", Metabolitelist[i,], "$", sep = ""), kegg_compounds$NAME, ignore.case = TRUE),]
  if (nrow(kegg) != 0){
    kegg$met <- paste0(i)
    x <- rbind(x, kegg)
  }
  else rm(kegg)
}
rownames(x) <- NULL
x <- x[-c(5:7,15:18,80:82, 278:287),]
# write_csv(x, "metuntruncated.csv")
# manually edited to get rid of duplicates/false IDs
```

```{r manually edited but has 24 missing}
truncatedKEGGmatches <- as.data.frame(read_csv("metuntruncated.csv"))
View(truncatedKEGGmatches)
missing_met_index <- c(2,5,7,11,12,13,19,20,21,28,30,31,32,33,34,36,45,56,61,65,69,70,78,79)
length(missing_met_index) #number of metabolites not matched 'yet'
# 2 - 1,4-D-xylobiose 1370
# 5 3-amino-2-piperidone not found at all
# 7 4-aminobutyric acid GABA 316
# 11 beta-alanine 97
# 12 L-3-Cyanoalanine or beta-cyano-L-alanine 2030
# 13 Carbonate Ion is CO3 with -2 charge; the closest thing is HCO3 Bicarbonate 274
# 19 D-malic acid 459
# 20 not used; D-maltitol is known as 4-O-α-glucopyranosyl-D-sorbitol; closest match would be D-sorbitol 708; notice how glucopryanosyl is in D-maltitol and Sophorose and Cellobiose
# 21 D-mannitol 368
# 28 galactinol 1090
# 30 (D-)galacto-hexodialdose 2577
# 31 not used; glucosyl glycerate is intermediate to glucosyl-3-phosphoglycerate; can also be made from 1-step synthesis from ADP-glucose (460) and d-glycerate (253) *below
# 32-34 not used; Glucosyl glycerol 1-3 skipped # need more info
# 36 Glyceric acid 253
# 45 not used; Leucrose 5-O-alpha-D-glucopyranosyl-D-fructose; close to Maltulose; 4-O-alpha-D-Glucopyranosyl-D-fructose or Turanose; 3-O-alpha-D-Glucopyranosyl-D-fructose # more info needed
# 56 L-threonic acid or L-threonate 1362
# 61 not used; Maltotriitol is O-α-D-Glucopyranosyl-(1→4)-O-α-D-glucopyranosyl-(1→4)-D-glucitol;
# 65 methyl phoshate CH3O4P-2; Formylphosphonate 14473
# 69 not used porphine not found
# 70 propylene glycol 536
# 78 and 79 not used; Tris 1 and 2 considered buffers
met <- c(2,7,11,12,13,19,21,28,30,36,56,65,70)
addKEGGmatches <- cbind(kegg_compounds[c(1370,316,97,2030,274,459,368,1090,2577,253,1362,14473,536),], met)
KEGGmatches <- rbind(truncatedKEGGmatches, addKEGGmatches)
KEGGmatches$met <- gsub("^.*\\.","", KEGGmatches$met)
KEGGmatches$met <- as.numeric(KEGGmatches$met)
Metabolitelist <- tibble::rownames_to_column(Metabolitelist, "met")
Metabolitelist$met <- as.numeric(Metabolitelist$met)
KEGGmatches <- KEGGmatches[,c(16,1:15)]
KEGGmatches <- merge(Metabolitelist,KEGGmatches, by = "met") # KEGGmatches now has all the matches possible 
KEGGmatches <- KEGGmatches[-14,]
```

```{r export} 
#exporting as csv
write_csv(KEGGmatches, "KEGGmatches.csv")
```

> 71 out of 83 known metabolites were matched to KEGG

### omu package for metabolomic analysis

1. We need to combine the counts with the KEGG compound names. First, we need to make the counts go from wide to long using dplyr and tidyr : omudata

2. We need to see metadata of each plot 
```{r}
omudata <- merge(EMSL_PNNL, KEGGmatches[,c(2,3)], by = "Metabolite", all = TRUE)
omudata <- omudata[,c(1,29,2:28)]
omudata <- omudata %>%
  rename(KEGG = COMPOUND)
metadatadf <- EMSL_PNNL[1,-1] %>%
  gather(Sample, Background, M_C_4_AB:O_H_32_AB)
metadatadf$Treatment <- str_sub(metadatadf$Sample, 3,3)
metadatadf$Background <- str_sub(metadatadf$Sample, 1,1)
metadatadf$Grouped <- str_sub(metadatadf$Sample,1,3)
write.csv(omudata, "EMSL_PNNL_plusKEGG.csv")
write.csv(metadatadf, "EMSL_PNNL_metadata.csv")
```

